### ISSUE TITLE
[1.12.2] nullpointer error crash on start up of game

### ISSUE THREAD

**Issue by engineer-256** [BluSunrize/ImmersiveEngineering#2672]
I crash on start up with this error: 

"The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game"

And here is the crashlog below:

[crash-2017-12-17_01.19.59-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1565352/crash-2017-12-17_01.19.59-client.txt)

**Comment by Xemnes-Keyethkateth** [comment]
having the same issue, it seems to only happen with forge version 14.23.1.2576+

**Comment by malte0811** [comment]
For now you can just use an older forge version. I'm not sure yet whether this is our fault or a bug in forge, I'll do some proper debugging later today.

**Comment by bs2609** [comment]
This doesn't seem right:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/models/smart/ConnLoader.java#L190

**Comment by msuguy71** [comment]
I am getting this bug also, but I am using forge 14.23.1.2578.  If I remove the IE mod, the game loads up.
[crash-2017-12-18_21.13.04-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1570089/crash-2017-12-18_21.13.04-client.txt)

**Comment by Pythonic-Rainbow** [comment]
> I am getting this bug also, but I am using forge 14.23.1.2578. If I remove the IE mod, the game loads up.
crash-2017-12-18_21.13.04-client.txt

Same

**Comment by GWSheridan** [comment]
+1 also getting this crash
its with the latest forge 14.23.1.2576 or higher

Crash report: https://pastebin.com/YRw3bY8G

**Comment by HorizonsMC** [comment]
This was fixed in Forge 2582 for anyone wanting to update past 2575.

**Comment by Pythonic-Rainbow** [comment]
Twitch Launcher says latest build is 2579.Do you know that if it works? @HorizonsMC

**Comment by OmarWazzan** [comment]
Any news on this fix?

**Comment by malte0811** [comment]
No. It's still the same as it was half a year ago: It's fixed for 1.12. 1.11 isn't supported any more, so it won't be fixed there.

**Comment by OmarWazzan** [comment]
Shame @malte0811, was looking forwards to using it.

**Comment by PulseBeat02** [comment]
I still get a crash when I play the latest 1.12.2 version of Forge, Immersive Engineering Mod, and Connected Textures Mod. Help Anyone?

**Comment by malte0811** [comment]
That is a completely different crash. It should be fixed by updating CTM or downgrading Forge.

**Comment by PulseBeat02** [comment]
Ok, I will post this as a different issue.
