### ISSUE TITLE
Minecraft server crash when load a chunk with IE machines

### ISSUE THREAD

**Issue by XemnasDestroyer** [BluSunrize/ImmersiveEngineering#4655]
### Description of the issue:
In my minecraft server, we have a chunk with all kind of items and machines from the IE mod. If someone get in the server, being alone in the server and he was on that specific chunk, the server crashes.

### Crashlog:
https://pastebin.com/q6BPxzAQ

### Versions & Modlist

IE Version: 1.16.4-4.1.2-129
Forge Version: 35.1.4

We tried this on singleplayer, and happens the same too. We have other mods, but we tried this without them and same thing happened.

Hope you can help me. Anyway, you did a great job with the mod, thank you <3

**Comment by mindforger** [comment]
looks like a (code) deadlock based on pipes and concurrent access.
 are you able to provide a Screenshot for reproduction?

**Comment by BluSunrize** [comment]
Please try updating to 1.16.5 and using release 131 of IE to see if this resolves the issue.

**Comment by XemnasDestroyer** [comment]
Ok, i'll try it asap, thx

**Comment by XemnasDestroyer** [comment]
Ok, the chunk is working with the 1.16.5 version (ImmersiveEngineering-1.16.5-4.2.1-131). The problem now is that the other mobs now doesnt work on the 1.16.5 forge version. Any ideas? Thx for the patience.

**Comment by BluSunrize** [comment]
IE doesn't add any mobs, so I can't help you there, sorry.

This issue is resolved.

**Comment by Nauclerus** [comment]
> looks like a (code) deadlock based on pipes and concurrent access.
> are you able to provide a Screenshot for reproduction?

This might indeed be it. I am using the exact same versions as OP and I'm seemingly having the exact same issue, allthough I don't crash, I just timeout from the server and the server itself freezes. As such I don't get a crashlog and that makes pinpointing the issues hard.

As I remove liquid holding pipes and pumps from my base the issue comes up less frequently, but still persists.
When I remove all liquid bearing IE machines, the issue seems to dissapear. I'm trying to recreate the exact cause as to why this happens.

It does not happens always and only happens when the chunks are unloaded and I load them in, be it by TPing to the affected chunks, any within render distance of the affected chunks or approaching the chunks on foot.

**Comment by Nauclerus** [comment]
> IE doesn't add any mobs, so I can't help you there, sorry.
> 
> This issue is resolved.

I think he mistyped here and meant mods, he also mentions the forge version pointing at the incompatibility with the 1.16.5 IE and his 1.16.4 modpack. Please reconsider reopening the issue

**Comment by BluSunrize** [comment]
If their other mods are not running on 1.16.5, that's not an IE issue.

If the original crash is reproducible with ImmersiveEngineering-1.16.5-4.2.1-131, I'm happy to reopen it, but otherwise I'll consider this fixed. We are not doing any further releases for 1.16.4 anyway.

**Comment by Nauclerus** [comment]
My client log sees certain packages being sent, but for some reason the pipes aren't being recognised as the proper blocks. 


[17:16:39] [Render thread/INFO]: Update tile packet received for position: BlockPos{x=630, y=61, z=1065} in world: minecraft:overworld, but no valid tile was found.

I had a couple dozen of these errors, all perfectly on the locations of the pipes

**Comment by Nauclerus** [comment]
> If their other mods are not running on 1.16.5, that's not an IE issue.
> 
> If the original crash is reproducible with ImmersiveEngineering-1.16.5-4.2.1-131, I'm happy to reopen it, but otherwise I'll consider this fixed. We are not doing any further releases for 1.16.4 anyway.

I understand that

**Comment by Nauclerus** [comment]
>  If their other mods are not running on 1.16.5, that's not an IE issue.
>  If the original crash is reproducible with ImmersiveEngineering-1.16.5-4.2.1-131, I'm happy to reopen it, but otherwise I'll consider this fixed. We are not doing any further releases for 1.16.4 anyway.
> 
 I understand that, but it's not about other mods not working, it's about this (the last for 1.16.4) being fundamentally broken in the way it handles its liquids in some ways. This would prevent people from even using the mod properly for this version, atleast in this iteration of IE. 
Don't take this as critique, I love your mod and this is precisely the reason why I'd like this fixed... to play it

**Comment by BluSunrize** [comment]
I already said, 1.16.4 is not receiving any more updates. Move to 1.16.5.
